servers = [
    "time.cloudflare.com",
    "1.ntp.ubuntu.com",
    "2.ntp.ubuntu.com",
    "3.ntp.ubuntu.com",
    "4.ntp.ubuntu.com",
    "time1.mbix.ca",
    "time2.mbix.ca",
    "time3.mbix.ca",
    "time.web-clock.ca",
    "ntp1.glypnod.com",
    "ohio.time.system76.com",
    "oregon.time.system76.com",
    "virginia.time.system76.com",
    "stratum1.time.cifelli.xyz",
    "time.cifelli.xyz",
    "ntp1.wiktel.com",
    "ntp2.wiktel.com",
    "time.txryan.com",
    "time.xargs.org",
]
